# Copyright (c) 2021 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
#
# This file contains baseline expectations
# for checked results by checkmetrics tool.
#
# values set specifically for packet.com c1.small worker.

[[metric]]
name = "boot-times"
type = "json"
description = "measure container lifecycle timings"
# Min and Max values to set a 'range' that
# the median of the CSV Results data must fall
# within (inclusive)
checkvar = ".\"boot-times\".Results | .[] | .\"to-workload\".Result"
checktype = "mean"
midval = 0.47
minpercent = 30.0
maxpercent = 30.0

[[metric]]
name = "memory-footprint"
type = "json"
description = "measure container average footprint"
# Min and Max values to set a 'range' that
# the median of the CSV Results data must fall
# within (inclusive)
checkvar = ".\"memory-footprint\".Results | .[] | .average.Result"
checktype = "mean"
midval = 122481.45
minpercent = 5.0
maxpercent = 5.0

[[metric]]
name = "memory-footprint-inside-container"
type = "json"
description = "measure memory inside the container"
# Min and Max values to set a 'range' that
# the median of the CSV Results data must fall
# within (inclusive)
checkvar = ".\"memory-footprint-inside-container\".Results | .[] | .memtotal.Result"
checktype = "mean"
midval = 4139564.0
minpercent = 5.0
maxpercent = 5.0

[[metric]]
name = "latency"
type = "json"
description = "measure network latency"
# Min and Max values to set a 'range' that
# the median of the CSV Results data must fall
# within (inclusive)
checkvar = ".\"latency\".Results | .[] | .latency.Result"
checktype = "mean"
midval = 0.81
minpercent = 20.0
maxpercent = 10.0

[[metric]]
name = "blogbench"
type = "json"
description = "measure container average of blogbench write"
# Min and Max values to set a 'range' that
# the median of the CSV Results data must fall
# within (inclusive)
checkvar = ".\"blogbench\".Results | .[] | .write.Result"
checktype = "mean"
midval = 1346.0
minpercent = 10.0
maxpercent = 10.0

[[metric]]
name = "fio"
type = "json"
description = "measure write 90 percentile using fio"
# Min and Max values to set a 'range' that
# the median of the CSV Results data must fall
# within (inclusive)
checkvar = ".\"fio\".Results | .[] | .write90percentile.Result"
checktype = "mean"
midval = 70557.0
minpercent = 70.0
maxpercent = 70.0

[[metric]]
name = "fio"
type = "json"
description = "measure write 95 percentile using fio"
# Min and Max values to set a 'range' that
# the median of the CSV Results data must fall
# within (inclusive)
checkvar = ".\"fio\".Results | .[] | .write95percentile.Result"
checktype = "mean"
midval = 87296.0
minpercent = 70.0
maxpercent = 70.0

[[metric]]
name = "blogbench"
type = "json"
description = "measure container average of blogbench read"
# Min and Max values to set a 'range' that
# the median of the CSV Results data must fall
# within (inclusive)
checkvar = ".\"blogbench\".Results | .[] | .read.Result"
checktype = "mean"
midval = 84119.0
minpercent = 10.0
maxpercent = 10.0

[[metric]]
name = "fio"
type = "json"
description = "measure read-io using fio"
# Min and Max values to set a 'range' that
# the median of the CSV Results data must fall
# within (inclusive)
checkvar = ".\"fio\".Results | .[] | .readio.Result"
checktype = "mean"
midval = 7811072.0
minpercent = 20.0
maxpercent = 20.0

[[metric]]
name = "fio"
type = "json"
description = "measure read-bw using fio"
# Min and Max values to set a 'range' that
# the median of the CSV Results data must fall
# within (inclusive)
checkvar = ".\"fio\".Results | .[] | .readbw.Result"
checktype = "mean"
midval = 113203942.0
minpercent = 25.0
maxpercent = 25.0

[[metric]]
name = "fio"
type = "json"
description = "measure write-io using fio"
# Min and Max values to set a 'range' that
# the median of the CSV Results data must fall
# within (inclusive)
checkvar = ".\"fio\".Results | .[] | .writeio.Result"
checktype = "mean"
midval = 2674688.0
minpercent = 20.0
maxpercent = 10.0

[[metric]]
name = "fio"
type = "json"
description = "measure write-bw using fio"
# Min and Max values to set a 'range' that
# the median of the CSV Results data must fall
# within (inclusive)
checkvar = ".\"fio\".Results | .[] | .writebw.Result"
checktype = "mean"
midval = 35543338.0
minpercent = 40.0
maxpercent = 30.0


[[metric]]
name = "network-iperf3"
type = "json"
description = "measure container bandwidth using iperf3"
# Min and Max values to set a 'range' that
# the median of the CSV Results data must fall
# within (inclusive)
checkvar = ".\"network-iperf3\".Results | .[] | .bandwidth.Result"
checktype = "mean"
midval = 61147291549.0
minpercent = 10.0
maxpercent = 10.0

[[metric]]
name = "fio"
type = "json"
description = "measure read 90 percentile using fio"
# Min and Max values to set a 'range' that
# the median of the CSV Results data must fall
# within (inclusive)
checkvar = ".\"fio\".Results | .[] | .read90percentile.Result"
checktype = "mean"
midval = 56668.0
minpercent = 50.0
maxpercent = 60.0

[[metric]]
name = "fio"
type = "json"
description = "measure read 95 percentile using fio"
# Min and Max values to set a 'range' that
# the median of the CSV Results data must fall
# within (inclusive)
checkvar = ".\"fio\".Results | .[] | .read95percentile.Result"
checktype = "mean"
midval = 84454.0
minpercent = 60.0
maxpercent = 60.0

[[metric]]
name = "network-iperf3"
type = "json"
description = "measure container cpu utilization using iperf3"
# Min and Max values to set a 'range' that
# the median of the CSV Results data must fall
# within (inclusive)
checkvar = ".\"network-iperf3\".Results | .[] | .cpu.Result"
checktype = "mean"
midval = 99.0
minpercent = 10.0
maxpercent = 10.0

[[metric]]
name = "network-iperf3"
type = "json"
description = "measure container parallel bandwidth using iperf3"
# Min and Max values to set a 'range' that
# the median of the CSV Results data must fall
# within (inclusive)
checkvar = ".\"network-iperf3\".Results | .[] | .parallel.Result"
checktype = "mean"
midval = 75296926250.0
minpercent = 10.0
maxpercent = 10.0

[[metric]]
name = "network-iperf3"
type = "json"
description = "measure container jitter using iperf3"
# Min and Max values to set a 'range' that
# the median of the CSV Results data must fall
# within (inclusive)
checkvar = ".\"network-iperf3\".Results | .[] | .jitter.Result"
checktype = "mean"
midval = 0.039
minpercent = 60.0
maxpercent = 50.0

