#
# Copyright (c) 2017 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
#

dist: trusty

language: go
go_import_path: github.com/kata-containers/tests

go:
  - 1.8

before_script:
  - ".ci/setup.sh"
