# Copyright (c) 2018 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

# Set up an Ubuntu image with the components needed to run `fio`
# hadolint ignore=DL3007
FROM @UBUNTU_REGISTRY@/ubuntu:latest

# Version of the Dockerfile
LABEL DOCKERFILE_VERSION="1.0"

# Without this some of the package installs stop to try and ask questions...
#ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
	apt-get install -y --no-install-recommends fio && \
	apt-get remove -y unattended-upgrades && \
	apt-get clean && rm -rf /var/lib/apt/lists/*

# Pull in our actual worker scripts
COPY . /scripts

# By default generate the report
CMD ["/scripts/init.sh"]
