[package]
name = "check-markdown-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
comrak = "0.18"
clap = "3.0"
url = "2.3.1"
