apiVersion: kubeadm.k8s.io/v1beta2
kind: InitConfiguration
nodeRegistration:
  criSocket: CRI_RUNTIME_SOCKET
  kubeletExtraArgs:
    allowed-unsafe-sysctls: kernel.msg*,kernel.shm.*,net.*
    v: "4"
---
apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
kubernetesVersion: KUBERNETES_VERSION
networking:
  dnsDomain: cluster.local
  podSubnet: 10.244.0.0/16
  serviceSubnet: 10.96.0.0/12
---
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
cgroupDriver: CGROUP_DRIVER
systemReserved:
  cpu: 500m
  memory: 256Mi
kubeReserved:
  cpu: 500m
  memory: 256Mi
