#
# Copyright (c) 2020 Ant Group
#
# SPDX-License-Identifier: Apache-2.0
#

apiVersion: v1
kind: Pod
metadata:
  name: pod-oom
  namespace: default
spec:
  runtimeClassName: kata
  restartPolicy: Never
  containers:
    - image: containerstack/alpine-stress:latest
      imagePullPolicy: Always
      name: oom-test
      command: ["/bin/sh"]
      args: ["-c", "sleep 5; stress --vm 2 --vm-bytes 400M --timeout 60s"]
      resources:
        limits:
          memory: 100Mi
        requests:
          memory: 100Mi
